sidebar: left

excerpt_link: READ MORE

widgets:
  - mailchimp
  - tagcloud
  - recent_posts
  - archive

has_mailchimp: true

google_analytics: UA-42370265-1

menu:
  Home: /
  About: /about
